# Generated by Django 5.0 on 2024-01-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyCard',
            fields=[
                ('serial_number', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('priority_type', models.CharField(max_length=20)),
                ('time_needed', models.IntegerField(blank=True, null=True)),
                ('emergency_type', models.CharField(max_length=50)),
                ('location', models.CharField(default='Default Location', max_length=100)),
            ],
        ),
    ]
