# Generated by Django 4.1.10 on 2024-01-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycard',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
