# Generated by Django 4.1.10 on 2023-12-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pay', models.IntegerField()),
                ('mobile', models.TextField()),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
            ],
        ),
    ]
