# Generated by Django 4.1.10 on 2024-01-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DisasterStories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=200)),
                ("date", models.DateTimeField()),
                ("description", models.TextField()),
            ],
        ),
    ]
